name = "PolynomialEquations"
uuid = "733821c1-d247-45d5-83ff-82f23d557536"
authors = ["Zdenek Hurak"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
